"use client";
// GENERATED by `mdmx generate` — do not edit.
import Callout from "../components/mdmx/Callout";
import { Stat } from "../components/mdmx/Stat";

/** Author components for the editor canvas and the dashboard mount. */
export const components = { Callout, Stat };
