// GENERATED by `mdmx generate` — do not edit.
import { Registry, type RegistrySpec } from "@mdmx/core";
import Callout from "../components/mdmx/Callout";
import { Stat } from "../components/mdmx/Stat";

export const spec: RegistrySpec = {
  "mdmxRegistryVersion": 1,
  "hash": "22036803a2eaa056",
  "components": [
    {
      "name": "Callout",
      "category": "Content",
      "icon": "alert-circle",
      "description": "Highlighted box for notes and warnings",
      "source": "components/mdmx/Callout.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Optional title"
          },
          "description": "Short label shown in the header"
        },
        {
          "name": "variant",
          "required": true,
          "control": {
            "type": "select",
            "options": [
              "info",
              "warn",
              "danger"
            ]
          },
          "default": "info"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "Stat",
      "category": "Data",
      "icon": "trending-up",
      "description": "A single headline metric",
      "source": "components/mdmx/Stat.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "value",
          "required": true,
          "control": {
            "type": "text"
          },
          "description": "The headline number, preformatted"
        },
        {
          "name": "label",
          "required": true,
          "control": {
            "type": "text"
          }
        },
        {
          "name": "trend",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "up",
              "down",
              "flat"
            ]
          }
        },
        {
          "name": "delta",
          "required": false,
          "control": {
            "type": "number"
          }
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    }
  ]
};

export const registry = new Registry(spec);

/** Author components for server rendering (public pages). */
export const serverComponents = { Callout, Stat };

/** Historical alias for `serverComponents`. */
export const components = serverComponents;
