"use client";
// GENERATED by `mdmx generate` — do not edit.
import Callout from "../components/mdmx/Callout";
import { CallToAction } from "../components/mdmx/CallToAction";
import Column from "../components/mdmx/Column";
import { FAQ } from "../components/mdmx/FAQ";
import { FAQItem } from "../components/mdmx/FAQItem";
import { Feature } from "../components/mdmx/Feature";
import { FeatureGrid } from "../components/mdmx/FeatureGrid";
import { Hero } from "../components/mdmx/Hero";
import { Html } from "../components/mdmx/Html";
import { LogoCloud } from "../components/mdmx/LogoCloud";
import { Newsletter } from "../components/mdmx/Newsletter";
import { PricingTable } from "../components/mdmx/PricingTable";
import { PricingTier } from "../components/mdmx/PricingTier";
import { Stat } from "../components/mdmx/Stat";
import { StatsBand } from "../components/mdmx/StatsBand";
import { Testimonial } from "../components/mdmx/Testimonial";
import TwoColumn from "../components/mdmx/TwoColumn";

/** Author components for the editor canvas and the dashboard mount. */
export const components = { Callout, CallToAction, Column, FAQ, FAQItem, Feature, FeatureGrid, Hero, Html, LogoCloud, Newsletter, PricingTable, PricingTier, Stat, StatsBand, Testimonial, TwoColumn };
