// GENERATED by `mdmx generate` — do not edit.
import { Registry, type RegistrySpec } from "@mdmx/core";
import { Accordion } from "../components/mdmx/Accordion";
import { AccordionItem } from "../components/mdmx/AccordionItem";
import { Alert } from "../components/mdmx/Alert";
import { AspectRatio } from "../components/mdmx/AspectRatio";
import { Avatar } from "../components/mdmx/Avatar";
import { Badge } from "../components/mdmx/Badge";
import { Button } from "../components/mdmx/Button";
import Callout from "../components/mdmx/Callout";
import { CallToAction } from "../components/mdmx/CallToAction";
import { Card } from "../components/mdmx/Card";
import { Collapsible } from "../components/mdmx/Collapsible";
import Column from "../components/mdmx/Column";
import { Empty } from "../components/mdmx/Empty";
import { FAQ } from "../components/mdmx/FAQ";
import { FAQItem } from "../components/mdmx/FAQItem";
import { Feature } from "../components/mdmx/Feature";
import { FeatureGrid } from "../components/mdmx/FeatureGrid";
import { Hero } from "../components/mdmx/Hero";
import { HoverCard } from "../components/mdmx/HoverCard";
import { Html } from "../components/mdmx/Html";
import { Item } from "../components/mdmx/Item";
import { Kbd } from "../components/mdmx/Kbd";
import { LogoCloud } from "../components/mdmx/LogoCloud";
import { Newsletter } from "../components/mdmx/Newsletter";
import { PricingTable } from "../components/mdmx/PricingTable";
import { PricingTier } from "../components/mdmx/PricingTier";
import { Progress } from "../components/mdmx/Progress";
import { Separator } from "../components/mdmx/Separator";
import { Skeleton } from "../components/mdmx/Skeleton";
import { Spinner } from "../components/mdmx/Spinner";
import { Stat } from "../components/mdmx/Stat";
import { StatsBand } from "../components/mdmx/StatsBand";
import { Tab } from "../components/mdmx/Tab";
import { Table } from "../components/mdmx/Table";
import { Tabs } from "../components/mdmx/Tabs";
import { Testimonial } from "../components/mdmx/Testimonial";
import { Toggle } from "../components/mdmx/Toggle";
import { Tooltip } from "../components/mdmx/Tooltip";
import TwoColumn from "../components/mdmx/TwoColumn";

export const spec: RegistrySpec = {
  "mdmxRegistryVersion": 3,
  "hash": "b2dbf755b2f0a7ec",
  "components": [
    {
      "name": "Accordion",
      "category": "UI",
      "icon": "chevrons-down-up",
      "description": "Stacked, expandable sections (holds AccordionItem blocks)",
      "source": "components/mdmx/Accordion.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": [
          "AccordionItem"
        ]
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "AccordionItem",
      "category": "UI",
      "icon": "chevron-down",
      "description": "One expandable section inside an Accordion",
      "source": "components/mdmx/AccordionItem.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Section title"
          },
          "default": "Section"
        },
        {
          "name": "open",
          "required": false,
          "control": {
            "type": "boolean"
          },
          "description": "Start expanded",
          "default": false
        }
      ],
      "constraints": {
        "allowedParents": [
          "Accordion"
        ],
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "title": "What is a block?",
        "children": "A registered component the editor can insert."
      }
    },
    {
      "name": "Alert",
      "category": "UI",
      "icon": "alert-triangle",
      "description": "Callout with an optional title and icon",
      "source": "components/mdmx/Alert.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Heads up"
          }
        },
        {
          "name": "variant",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "default",
              "destructive"
            ]
          },
          "default": "default"
        },
        {
          "name": "icon",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "💡"
          },
          "description": "Emoji or short glyph shown before the title"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "title": "Heads up",
        "children": "Something worth knowing."
      }
    },
    {
      "name": "AspectRatio",
      "category": "UI",
      "icon": "crop",
      "description": "An image cropped to a fixed aspect ratio",
      "source": "components/mdmx/AspectRatio.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "src",
          "required": false,
          "control": {
            "type": "image"
          },
          "description": "Image URL (pick from the media library)",
          "default": "/media/placeholder.svg"
        },
        {
          "name": "alt",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Describe the image"
          }
        },
        {
          "name": "ratio",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "16/9",
              "4/3",
              "1/1",
              "3/2",
              "21/9"
            ]
          },
          "default": "16/9"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "src": "/media/placeholder.svg",
        "alt": "Placeholder"
      }
    },
    {
      "name": "Avatar",
      "category": "UI",
      "icon": "user",
      "description": "A round profile image with initials fallback",
      "source": "components/mdmx/Avatar.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "src",
          "required": false,
          "control": {
            "type": "image"
          },
          "description": "Image URL (pick from the media library)"
        },
        {
          "name": "fallback",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "JD"
          },
          "description": "Initials shown while the image loads or when there is none",
          "default": "JD"
        },
        {
          "name": "alt",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Who is pictured"
          },
          "showIf": {
            "prop": "src"
          }
        },
        {
          "name": "size",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "sm",
              "default",
              "lg"
            ]
          },
          "default": "default"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "fallback": "JD"
      }
    },
    {
      "name": "Badge",
      "category": "UI",
      "icon": "tag",
      "description": "A small status label, optionally linking somewhere",
      "source": "components/mdmx/Badge.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "label",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "New"
          },
          "default": "New"
        },
        {
          "name": "variant",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "default",
              "secondary",
              "destructive",
              "outline",
              "ghost",
              "link"
            ]
          },
          "default": "default"
        },
        {
          "name": "href",
          "required": false,
          "control": {
            "type": "link",
            "placeholder": "/changelog"
          },
          "description": "Makes the badge a link"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "label": "New"
      }
    },
    {
      "name": "Button",
      "category": "UI",
      "icon": "mouse-pointer-click",
      "description": "A button, optionally linking somewhere",
      "source": "components/mdmx/Button.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "label",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Click me"
          },
          "default": "Button"
        },
        {
          "name": "href",
          "required": false,
          "control": {
            "type": "link",
            "placeholder": "/docs"
          },
          "description": "Where the button links to; leave empty for a plain button"
        },
        {
          "name": "variant",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "default",
              "outline",
              "secondary",
              "ghost",
              "destructive",
              "link"
            ]
          },
          "default": "default"
        },
        {
          "name": "size",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "sm",
              "default",
              "lg"
            ]
          },
          "default": "default"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "label": "Get started"
      }
    },
    {
      "name": "Callout",
      "category": "Content",
      "icon": "alert-circle",
      "description": "Highlighted box for notes and warnings",
      "source": "components/mdmx/Callout.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Optional title"
          },
          "description": "Short label shown in the header"
        },
        {
          "name": "variant",
          "required": true,
          "control": {
            "type": "select",
            "options": [
              "info",
              "warn",
              "danger"
            ]
          },
          "default": "info"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "variant": "info",
        "title": "Example",
        "children": "Sample text"
      }
    },
    {
      "name": "CallToAction",
      "category": "Marketing",
      "icon": "megaphone",
      "description": "Banner with a heading, supporting text, and one action button",
      "source": "components/mdmx/CallToAction.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "heading",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Ready to start?"
          },
          "default": "Ready to start?"
        },
        {
          "name": "buttonLabel",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Button text"
          },
          "default": "Get started"
        },
        {
          "name": "buttonHref",
          "required": false,
          "control": {
            "type": "link",
            "placeholder": "/signup"
          },
          "default": "#"
        },
        {
          "name": "variant",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "solid",
              "soft"
            ]
          },
          "default": "solid"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "heading": "Ready to dive in?",
        "buttonLabel": "Start now",
        "buttonHref": "#",
        "variant": "solid",
        "children": "Start authoring with your own components today."
      }
    },
    {
      "name": "Card",
      "category": "UI",
      "icon": "square",
      "description": "A bordered card with an optional header; holds any blocks",
      "source": "components/mdmx/Card.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Card title"
          }
        },
        {
          "name": "description",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Optional description"
          }
        },
        {
          "name": "size",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "default",
              "sm"
            ]
          },
          "default": "default"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "title": "Card title",
        "description": "A short description.",
        "children": "Card body."
      }
    },
    {
      "name": "Collapsible",
      "category": "UI",
      "icon": "chevrons-up-down",
      "description": "A section that folds away behind a toggle",
      "source": "components/mdmx/Collapsible.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Show details"
          },
          "description": "The toggle's label",
          "default": "Details"
        },
        {
          "name": "open",
          "required": false,
          "control": {
            "type": "boolean"
          },
          "description": "Start expanded",
          "default": false
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "title": "Show details",
        "children": "Hidden until opened."
      }
    },
    {
      "name": "Column",
      "category": "Layout",
      "icon": "square",
      "description": "A column inside TwoColumn",
      "source": "components/mdmx/Column.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [],
      "constraints": {
        "allowedParents": [
          "TwoColumn"
        ],
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "Empty",
      "category": "UI",
      "icon": "inbox",
      "description": "An empty-state placeholder with a title and description",
      "source": "components/mdmx/Empty.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Nothing here yet"
          },
          "default": "Nothing here yet"
        },
        {
          "name": "description",
          "required": false,
          "control": {
            "type": "textarea",
            "placeholder": "What to do about it"
          }
        },
        {
          "name": "icon",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "📭"
          },
          "description": "Emoji or short glyph"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "title": "Nothing here yet",
        "description": "Add something to get started."
      }
    },
    {
      "name": "FAQ",
      "category": "Marketing",
      "icon": "help-circle",
      "description": "A list of question/answer items",
      "source": "components/mdmx/FAQ.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": [
          "FAQItem"
        ]
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "FAQItem",
      "category": "Marketing",
      "icon": "help-circle",
      "description": "One question/answer inside an FAQ",
      "source": "components/mdmx/FAQItem.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "question",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Frequently asked question?"
          },
          "default": "Question?"
        },
        {
          "name": "open",
          "required": false,
          "control": {
            "type": "boolean"
          },
          "description": "Start expanded",
          "default": true
        }
      ],
      "constraints": {
        "allowedParents": [
          "FAQ"
        ],
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "question": "How does it work?",
        "children": "Like this."
      }
    },
    {
      "name": "Feature",
      "category": "Marketing",
      "icon": "check-circle",
      "description": "A single feature card inside a FeatureGrid",
      "source": "components/mdmx/Feature.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Feature title"
          },
          "default": "Feature"
        },
        {
          "name": "icon",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "✨"
          },
          "description": "Emoji or short glyph shown above the title"
        }
      ],
      "constraints": {
        "allowedParents": [
          "FeatureGrid"
        ],
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "title": "Fast",
        "icon": "⚡",
        "children": "Ships in seconds."
      }
    },
    {
      "name": "FeatureGrid",
      "category": "Marketing",
      "icon": "grid",
      "description": "A responsive grid of Feature cards",
      "source": "components/mdmx/FeatureGrid.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [
        {
          "name": "columns",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "2",
              "3",
              "4"
            ]
          },
          "default": "3"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": [
          "Feature"
        ]
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "Hero",
      "category": "Marketing",
      "icon": "layout",
      "description": "Headline section with title, subtitle, and call-to-action buttons",
      "source": "components/mdmx/Hero.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "eyebrow",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Eyebrow label"
          },
          "description": "Small label above the title"
        },
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Headline"
          },
          "default": "Headline"
        },
        {
          "name": "subtitle",
          "required": false,
          "control": {
            "type": "textarea",
            "placeholder": "Supporting subtitle"
          }
        },
        {
          "name": "primaryLabel",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Primary button"
          }
        },
        {
          "name": "primaryHref",
          "required": false,
          "control": {
            "type": "link",
            "placeholder": "/start"
          },
          "showIf": {
            "prop": "primaryLabel"
          }
        },
        {
          "name": "secondaryLabel",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Secondary button"
          }
        },
        {
          "name": "secondaryHref",
          "required": false,
          "control": {
            "type": "link",
            "placeholder": "/docs"
          },
          "showIf": {
            "prop": "secondaryLabel"
          }
        },
        {
          "name": "align",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "left",
              "center"
            ]
          },
          "default": "center"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "eyebrow": "Now in beta",
        "title": "Ship content at the speed of git",
        "subtitle": "Edit your components as blocks. Commit canonical MDMX.",
        "primaryLabel": "Get started",
        "secondaryLabel": "Read the docs"
      }
    },
    {
      "name": "HoverCard",
      "category": "UI",
      "icon": "message-circle",
      "description": "Text that reveals a card on hover",
      "source": "components/mdmx/HoverCard.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Card title"
          },
          "description": "Card heading"
        },
        {
          "name": "content",
          "required": false,
          "control": {
            "type": "textarea",
            "placeholder": "Card body"
          },
          "description": "Card body, shown on hover",
          "default": "Card body"
        },
        {
          "name": "side",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "top",
              "right",
              "bottom",
              "left"
            ]
          },
          "default": "bottom"
        },
        {
          "name": "align",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "start",
              "center",
              "end"
            ]
          },
          "default": "center"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live",
        "interactive": true
      },
      "preview": {
        "title": "MDMX",
        "content": "A git-native CMS for Next.js.",
        "children": "Hover over me"
      }
    },
    {
      "name": "Html",
      "category": "Advanced",
      "icon": "code",
      "description": "Custom HTML block (sanitized on render)",
      "source": "components/mdmx/Html.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "code",
          "required": false,
          "control": {
            "type": "textarea",
            "placeholder": "<div>…</div>"
          },
          "description": "Raw HTML, sanitized before render",
          "default": ""
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "code": "<div style=\"padding:12px;border-radius:10px;background:#eef2ff\">Custom <strong>HTML</strong> block</div>"
      }
    },
    {
      "name": "Item",
      "category": "UI",
      "icon": "list",
      "description": "A list row with a title, description, and icon",
      "source": "components/mdmx/Item.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Item title"
          },
          "default": "Item"
        },
        {
          "name": "description",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Optional description"
          }
        },
        {
          "name": "icon",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "📦"
          },
          "description": "Emoji or short glyph shown on the left"
        },
        {
          "name": "variant",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "default",
              "outline",
              "muted"
            ]
          },
          "default": "outline"
        },
        {
          "name": "size",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "default",
              "sm",
              "xs"
            ]
          },
          "default": "default"
        },
        {
          "name": "href",
          "required": false,
          "control": {
            "type": "link",
            "placeholder": "/docs/item"
          },
          "description": "Makes the row a link"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "title": "An item",
        "description": "With a short description."
      }
    },
    {
      "name": "Kbd",
      "category": "UI",
      "icon": "keyboard",
      "description": "A keyboard shortcut",
      "source": "components/mdmx/Kbd.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "keys",
          "required": false,
          "control": {
            "type": "list",
            "item": {
              "type": "text"
            }
          },
          "description": "One key per entry, e.g. ⌘ and K",
          "default": [
            "⌘",
            "K"
          ]
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "keys": [
          "⌘",
          "K"
        ]
      }
    },
    {
      "name": "LogoCloud",
      "category": "Marketing",
      "icon": "image",
      "description": "A row of customer or partner logos (by name)",
      "source": "components/mdmx/LogoCloud.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Trusted by teams at"
          }
        },
        {
          "name": "names",
          "required": false,
          "control": {
            "type": "list",
            "item": {
              "type": "text"
            }
          },
          "description": "Company names, one per entry"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "title": "Trusted by teams at",
        "names": [
          "Acme",
          "Globex",
          "Initech",
          "Umbrella",
          "Hooli"
        ]
      }
    },
    {
      "name": "Newsletter",
      "category": "Marketing",
      "icon": "mail",
      "description": "Email signup band",
      "source": "components/mdmx/Newsletter.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "heading",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Stay in the loop"
          },
          "default": "Stay in the loop"
        },
        {
          "name": "buttonLabel",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Subscribe"
          },
          "default": "Subscribe"
        },
        {
          "name": "placeholder",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "you@example.com"
          }
        },
        {
          "name": "note",
          "required": false,
          "control": {
            "type": "textarea",
            "placeholder": "No spam. Unsubscribe anytime."
          }
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "heading": "Stay in the loop",
        "buttonLabel": "Subscribe",
        "note": "Product updates, roughly monthly."
      }
    },
    {
      "name": "PricingTable",
      "category": "Marketing",
      "icon": "credit-card",
      "description": "A row of pricing tiers",
      "source": "components/mdmx/PricingTable.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [
        {
          "name": "columns",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "2",
              "3",
              "4"
            ]
          },
          "default": "3"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": [
          "PricingTier"
        ]
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "PricingTier",
      "category": "Marketing",
      "icon": "tag",
      "description": "One plan inside a PricingTable",
      "source": "components/mdmx/PricingTier.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "name",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Plan name"
          },
          "default": "Plan"
        },
        {
          "name": "price",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "$0"
          },
          "default": "$0"
        },
        {
          "name": "period",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "mo"
          }
        },
        {
          "name": "ctaLabel",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Choose plan"
          }
        },
        {
          "name": "ctaHref",
          "required": false,
          "control": {
            "type": "link",
            "placeholder": "/signup"
          },
          "showIf": {
            "prop": "ctaLabel"
          }
        },
        {
          "name": "featured",
          "required": false,
          "control": {
            "type": "boolean"
          },
          "default": false
        }
      ],
      "constraints": {
        "allowedParents": [
          "PricingTable"
        ],
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "name": "Starter",
        "price": "$0",
        "period": "mo",
        "ctaLabel": "Choose plan",
        "children": "Everything you need to get going."
      }
    },
    {
      "name": "Progress",
      "category": "UI",
      "icon": "loader",
      "description": "A progress bar with an optional label",
      "source": "components/mdmx/Progress.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "value",
          "required": true,
          "control": {
            "type": "number",
            "min": 0,
            "max": 100,
            "step": 1
          },
          "description": "0–100",
          "default": 50
        },
        {
          "name": "label",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Uploading"
          }
        },
        {
          "name": "showValue",
          "required": false,
          "control": {
            "type": "boolean"
          },
          "default": true
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "value": 62,
        "label": "Progress"
      }
    },
    {
      "name": "Separator",
      "category": "UI",
      "icon": "minus",
      "description": "A horizontal rule, optionally labeled",
      "source": "components/mdmx/Separator.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "label",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "or"
          },
          "description": "Optional centered label",
          "showIf": {
            "prop": "orientation",
            "eq": "horizontal"
          }
        },
        {
          "name": "orientation",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "horizontal",
              "vertical"
            ]
          },
          "default": "horizontal"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "Skeleton",
      "category": "UI",
      "icon": "loader",
      "description": "A loading placeholder",
      "source": "components/mdmx/Skeleton.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "shape",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "text",
              "rect",
              "circle"
            ]
          },
          "default": "text"
        },
        {
          "name": "lines",
          "required": false,
          "control": {
            "type": "number",
            "min": 1,
            "max": 8,
            "step": 1
          },
          "description": "Number of lines when shape is \"text\"",
          "default": 3,
          "showIf": {
            "prop": "shape",
            "eq": "text"
          }
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "Spinner",
      "category": "UI",
      "icon": "loader",
      "description": "A loading indicator with an optional label",
      "source": "components/mdmx/Spinner.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "label",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Loading…"
          }
        },
        {
          "name": "size",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "sm",
              "default",
              "lg"
            ]
          },
          "default": "default"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "label": "Loading…"
      }
    },
    {
      "name": "Stat",
      "category": "Data",
      "icon": "trending-up",
      "description": "A single headline metric",
      "source": "components/mdmx/Stat.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "value",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "27ms"
          },
          "description": "The headline number, preformatted",
          "default": "0"
        },
        {
          "name": "label",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "What the number measures"
          },
          "default": "Label"
        },
        {
          "name": "trend",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "up",
              "down",
              "flat"
            ]
          }
        },
        {
          "name": "delta",
          "required": false,
          "control": {
            "type": "number",
            "step": 0.1
          }
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "value": "27ms",
        "label": "median save-to-commit",
        "trend": "up",
        "delta": 4
      }
    },
    {
      "name": "StatsBand",
      "category": "Marketing",
      "icon": "bar-chart-2",
      "description": "A band of headline metrics (holds Stat blocks)",
      "source": "components/mdmx/StatsBand.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Optional band title"
          }
        },
        {
          "name": "columns",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "2",
              "3",
              "4"
            ]
          },
          "default": "3"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": [
          "Stat"
        ]
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "Tab",
      "category": "UI",
      "icon": "panel-top",
      "description": "One panel inside Tabs",
      "source": "components/mdmx/Tab.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Overview"
          },
          "description": "Must match one of the parent Tabs' titles",
          "default": "Overview"
        }
      ],
      "constraints": {
        "allowedParents": [
          "Tabs"
        ],
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "title": "Overview",
        "children": "Panel content."
      }
    },
    {
      "name": "Table",
      "category": "UI",
      "icon": "table",
      "description": "A simple data table (headings + rows)",
      "source": "components/mdmx/Table.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "columns",
          "required": false,
          "control": {
            "type": "list",
            "item": {
              "type": "text"
            }
          },
          "description": "Column headings",
          "default": [
            "Plan",
            "Price"
          ]
        },
        {
          "name": "rows",
          "required": false,
          "control": {
            "type": "list",
            "item": {
              "type": "list",
              "item": {
                "type": "text"
              }
            }
          },
          "description": "Rows of cells, in column order",
          "default": [
            [
              "Starter",
              "$0"
            ]
          ]
        },
        {
          "name": "caption",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Optional caption"
          }
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "columns": [
          "Plan",
          "Price",
          "Seats"
        ],
        "rows": [
          [
            "Starter",
            "$0",
            "1"
          ],
          [
            "Team",
            "$29",
            "10"
          ],
          [
            "Enterprise",
            "Custom",
            "Unlimited"
          ]
        ]
      }
    },
    {
      "name": "Tabs",
      "category": "UI",
      "icon": "panel-top",
      "description": "Tabbed panels (holds Tab blocks whose titles match)",
      "source": "components/mdmx/Tabs.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [
        {
          "name": "tabs",
          "required": false,
          "control": {
            "type": "list",
            "item": {
              "type": "text"
            }
          },
          "description": "Tab titles — each matches a Tab block's title",
          "default": [
            "Overview",
            "Details"
          ]
        },
        {
          "name": "variant",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "default",
              "line"
            ]
          },
          "default": "default"
        },
        {
          "name": "orientation",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "horizontal",
              "vertical"
            ]
          },
          "default": "horizontal"
        },
        {
          "name": "defaultTab",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Overview"
          },
          "description": "Title of the tab shown first (defaults to the first)"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": [
          "Tab"
        ]
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "tabs": [
          "Overview",
          "Details"
        ]
      }
    },
    {
      "name": "Testimonial",
      "category": "Marketing",
      "icon": "message-square",
      "description": "A customer quote with attribution",
      "source": "components/mdmx/Testimonial.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "author",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Jane Doe"
          },
          "default": "Jane Doe"
        },
        {
          "name": "role",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "CTO, Acme"
          }
        },
        {
          "name": "avatar",
          "required": false,
          "control": {
            "type": "image"
          }
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "author": "Jane Doe",
        "role": "CTO, Acme",
        "children": "MDMX let our writers ship landing pages without touching the build."
      }
    },
    {
      "name": "Toggle",
      "category": "UI",
      "icon": "toggle-left",
      "description": "A two-state button",
      "source": "components/mdmx/Toggle.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "label",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Bold"
          },
          "default": "Toggle"
        },
        {
          "name": "pressed",
          "required": false,
          "control": {
            "type": "boolean"
          },
          "description": "Start pressed",
          "default": false
        },
        {
          "name": "variant",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "default",
              "outline"
            ]
          },
          "default": "outline"
        },
        {
          "name": "size",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "sm",
              "default",
              "lg"
            ]
          },
          "default": "default"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      },
      "preview": {
        "label": "Toggle me"
      }
    },
    {
      "name": "Tooltip",
      "category": "UI",
      "icon": "info",
      "description": "Text with a tooltip on hover",
      "source": "components/mdmx/Tooltip.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "content",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Helpful detail"
          },
          "description": "The tooltip text",
          "default": "Tooltip"
        },
        {
          "name": "side",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "top",
              "right",
              "bottom",
              "left"
            ]
          },
          "default": "top"
        },
        {
          "name": "align",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "start",
              "center",
              "end"
            ]
          },
          "default": "center"
        },
        {
          "name": "sideOffset",
          "required": false,
          "control": {
            "type": "number",
            "min": 0,
            "max": 32,
            "step": 1
          },
          "description": "Distance from the trigger, in pixels",
          "default": 4
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live",
        "interactive": true
      },
      "preview": {
        "content": "A tooltip",
        "children": "Hover me"
      }
    },
    {
      "name": "TwoColumn",
      "category": "Layout",
      "icon": "columns",
      "description": "Two side-by-side columns",
      "source": "components/mdmx/TwoColumn.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [
        {
          "name": "ratio",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "1:1",
              "1:2",
              "2:1"
            ]
          },
          "description": "Width ratio of the two columns",
          "default": "1:1"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": [
          "Column"
        ]
      },
      "render": {
        "mode": "live"
      }
    }
  ],
  "collections": [
    {
      "name": "posts",
      "dir": "content/posts",
      "fields": [
        {
          "name": "title",
          "required": true,
          "control": {
            "type": "text"
          }
        },
        {
          "name": "status",
          "required": true,
          "control": {
            "type": "select",
            "options": [
              "draft",
              "private",
              "published"
            ]
          },
          "default": "draft"
        },
        {
          "name": "slug",
          "required": false,
          "control": {
            "type": "text"
          }
        },
        {
          "name": "description",
          "required": false,
          "control": {
            "type": "textarea"
          }
        },
        {
          "name": "coverImage",
          "required": false,
          "control": {
            "type": "image"
          },
          "description": "Pick from the media library (Browse…)"
        }
      ]
    }
  ]
};

export const registry = new Registry(spec);

/** Author components for server rendering (public pages). */
export const serverComponents = { Accordion, AccordionItem, Alert, AspectRatio, Avatar, Badge, Button, Callout, CallToAction, Card, Collapsible, Column, Empty, FAQ, FAQItem, Feature, FeatureGrid, Hero, HoverCard, Html, Item, Kbd, LogoCloud, Newsletter, PricingTable, PricingTier, Progress, Separator, Skeleton, Spinner, Stat, StatsBand, Tab, Table, Tabs, Testimonial, Toggle, Tooltip, TwoColumn };

/** Historical alias for `serverComponents`. */
export const components = serverComponents;
