// GENERATED by `mdmx generate` — do not edit.
import { Registry, type RegistrySpec } from "@mdmx/core";
import Callout from "../components/mdmx/Callout";
import { CallToAction } from "../components/mdmx/CallToAction";
import Column from "../components/mdmx/Column";
import { FAQ } from "../components/mdmx/FAQ";
import { FAQItem } from "../components/mdmx/FAQItem";
import { Feature } from "../components/mdmx/Feature";
import { FeatureGrid } from "../components/mdmx/FeatureGrid";
import { Hero } from "../components/mdmx/Hero";
import { Html } from "../components/mdmx/Html";
import { LogoCloud } from "../components/mdmx/LogoCloud";
import { Newsletter } from "../components/mdmx/Newsletter";
import { PricingTable } from "../components/mdmx/PricingTable";
import { PricingTier } from "../components/mdmx/PricingTier";
import { Stat } from "../components/mdmx/Stat";
import { StatsBand } from "../components/mdmx/StatsBand";
import { Testimonial } from "../components/mdmx/Testimonial";
import TwoColumn from "../components/mdmx/TwoColumn";

export const spec: RegistrySpec = {
  "mdmxRegistryVersion": 1,
  "hash": "059f523d22be4ec1",
  "components": [
    {
      "name": "Callout",
      "category": "Content",
      "icon": "alert-circle",
      "description": "Highlighted box for notes and warnings",
      "source": "components/mdmx/Callout.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Optional title"
          },
          "description": "Short label shown in the header"
        },
        {
          "name": "variant",
          "required": true,
          "control": {
            "type": "select",
            "options": [
              "info",
              "warn",
              "danger"
            ]
          },
          "default": "info"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "CallToAction",
      "category": "Marketing",
      "icon": "megaphone",
      "description": "Banner with a heading, supporting text, and one action button",
      "source": "components/mdmx/CallToAction.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "heading",
          "required": true,
          "control": {
            "type": "text",
            "placeholder": "Ready to start?"
          }
        },
        {
          "name": "buttonLabel",
          "required": true,
          "control": {
            "type": "text",
            "placeholder": "Button text"
          }
        },
        {
          "name": "buttonHref",
          "required": true,
          "control": {
            "type": "link"
          }
        },
        {
          "name": "variant",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "solid",
              "soft"
            ]
          },
          "default": "solid"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "Column",
      "category": "Layout",
      "icon": "square",
      "description": "A column inside TwoColumn",
      "source": "components/mdmx/Column.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [],
      "constraints": {
        "allowedParents": [
          "TwoColumn"
        ],
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "FAQ",
      "category": "Marketing",
      "icon": "help-circle",
      "description": "A list of question/answer items",
      "source": "components/mdmx/FAQ.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": [
          "FAQItem"
        ]
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "FAQItem",
      "category": "Marketing",
      "icon": "help-circle",
      "description": "One question/answer inside an FAQ",
      "source": "components/mdmx/FAQItem.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "question",
          "required": true,
          "control": {
            "type": "text",
            "placeholder": "Frequently asked question?"
          }
        }
      ],
      "constraints": {
        "allowedParents": [
          "FAQ"
        ],
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "Feature",
      "category": "Marketing",
      "icon": "check-circle",
      "description": "A single feature card inside a FeatureGrid",
      "source": "components/mdmx/Feature.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "title",
          "required": true,
          "control": {
            "type": "text",
            "placeholder": "Feature title"
          }
        },
        {
          "name": "icon",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "✨"
          },
          "description": "Emoji or short glyph shown above the title"
        }
      ],
      "constraints": {
        "allowedParents": [
          "FeatureGrid"
        ],
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "FeatureGrid",
      "category": "Marketing",
      "icon": "grid",
      "description": "A responsive grid of Feature cards",
      "source": "components/mdmx/FeatureGrid.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [
        {
          "name": "columns",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "2",
              "3",
              "4"
            ]
          },
          "default": "3"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": [
          "Feature"
        ]
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "Hero",
      "category": "Marketing",
      "icon": "layout",
      "description": "Headline section with title, subtitle, and call-to-action buttons",
      "source": "components/mdmx/Hero.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "eyebrow",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Eyebrow label"
          },
          "description": "Small label above the title"
        },
        {
          "name": "title",
          "required": true,
          "control": {
            "type": "text",
            "placeholder": "Headline"
          }
        },
        {
          "name": "subtitle",
          "required": false,
          "control": {
            "type": "textarea",
            "placeholder": "Supporting subtitle"
          }
        },
        {
          "name": "primaryLabel",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Primary button"
          }
        },
        {
          "name": "primaryHref",
          "required": false,
          "control": {
            "type": "link"
          }
        },
        {
          "name": "secondaryLabel",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Secondary button"
          }
        },
        {
          "name": "secondaryHref",
          "required": false,
          "control": {
            "type": "link"
          }
        },
        {
          "name": "align",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "left",
              "center"
            ]
          },
          "default": "center"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "Html",
      "category": "Advanced",
      "icon": "code",
      "description": "Custom HTML block (sanitized on render)",
      "source": "components/mdmx/Html.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "code",
          "required": true,
          "control": {
            "type": "textarea",
            "placeholder": "<div>…</div>"
          },
          "description": "Raw HTML, sanitized before render"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "LogoCloud",
      "category": "Marketing",
      "icon": "image",
      "description": "A row of customer or partner logos (by name)",
      "source": "components/mdmx/LogoCloud.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Trusted by teams at"
          }
        },
        {
          "name": "names",
          "required": false,
          "control": {
            "type": "textarea",
            "placeholder": "Acme, Globex, Initech"
          },
          "description": "Comma-separated company names"
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "Newsletter",
      "category": "Marketing",
      "icon": "mail",
      "description": "Email signup band",
      "source": "components/mdmx/Newsletter.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "heading",
          "required": true,
          "control": {
            "type": "text",
            "placeholder": "Stay in the loop"
          }
        },
        {
          "name": "buttonLabel",
          "required": true,
          "control": {
            "type": "text",
            "placeholder": "Subscribe"
          }
        },
        {
          "name": "placeholder",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "you@example.com"
          }
        },
        {
          "name": "note",
          "required": false,
          "control": {
            "type": "textarea",
            "placeholder": "No spam. Unsubscribe anytime."
          }
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "PricingTable",
      "category": "Marketing",
      "icon": "credit-card",
      "description": "A row of pricing tiers",
      "source": "components/mdmx/PricingTable.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": [
          "PricingTier"
        ]
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "PricingTier",
      "category": "Marketing",
      "icon": "tag",
      "description": "One plan inside a PricingTable",
      "source": "components/mdmx/PricingTier.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "name",
          "required": true,
          "control": {
            "type": "text",
            "placeholder": "Plan name"
          }
        },
        {
          "name": "price",
          "required": true,
          "control": {
            "type": "text",
            "placeholder": "$0"
          }
        },
        {
          "name": "period",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "mo"
          }
        },
        {
          "name": "ctaLabel",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Choose plan"
          }
        },
        {
          "name": "ctaHref",
          "required": false,
          "control": {
            "type": "link"
          }
        },
        {
          "name": "featured",
          "required": false,
          "control": {
            "type": "boolean"
          },
          "default": false
        }
      ],
      "constraints": {
        "allowedParents": [
          "PricingTable"
        ],
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "Stat",
      "category": "Data",
      "icon": "trending-up",
      "description": "A single headline metric",
      "source": "components/mdmx/Stat.tsx",
      "children": {
        "policy": "none"
      },
      "props": [
        {
          "name": "value",
          "required": true,
          "control": {
            "type": "text"
          },
          "description": "The headline number, preformatted"
        },
        {
          "name": "label",
          "required": true,
          "control": {
            "type": "text"
          }
        },
        {
          "name": "trend",
          "required": false,
          "control": {
            "type": "select",
            "options": [
              "up",
              "down",
              "flat"
            ]
          }
        },
        {
          "name": "delta",
          "required": false,
          "control": {
            "type": "number"
          }
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "StatsBand",
      "category": "Marketing",
      "icon": "bar-chart-2",
      "description": "A band of headline metrics (holds Stat blocks)",
      "source": "components/mdmx/StatsBand.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [
        {
          "name": "title",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "Optional band title"
          }
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": [
          "Stat"
        ]
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "Testimonial",
      "category": "Marketing",
      "icon": "message-square",
      "description": "A customer quote with attribution",
      "source": "components/mdmx/Testimonial.tsx",
      "children": {
        "policy": "rich-text"
      },
      "props": [
        {
          "name": "author",
          "required": true,
          "control": {
            "type": "text",
            "placeholder": "Jane Doe"
          }
        },
        {
          "name": "role",
          "required": false,
          "control": {
            "type": "text",
            "placeholder": "CTO, Acme"
          }
        },
        {
          "name": "avatar",
          "required": false,
          "control": {
            "type": "image"
          }
        }
      ],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": null
      },
      "render": {
        "mode": "live"
      }
    },
    {
      "name": "TwoColumn",
      "category": "Layout",
      "icon": "columns",
      "description": "Two side-by-side columns",
      "source": "components/mdmx/TwoColumn.tsx",
      "children": {
        "policy": "blocks"
      },
      "props": [],
      "constraints": {
        "allowedParents": null,
        "allowedChildren": [
          "Column"
        ]
      },
      "render": {
        "mode": "live"
      }
    }
  ],
  "collections": [
    {
      "name": "posts",
      "dir": "content/posts",
      "fields": [
        {
          "name": "title",
          "required": true,
          "control": {
            "type": "text"
          }
        },
        {
          "name": "status",
          "required": true,
          "control": {
            "type": "select",
            "options": [
              "draft",
              "private",
              "published"
            ]
          },
          "default": "draft"
        },
        {
          "name": "slug",
          "required": false,
          "control": {
            "type": "text"
          }
        },
        {
          "name": "description",
          "required": false,
          "control": {
            "type": "textarea"
          }
        },
        {
          "name": "coverImage",
          "required": false,
          "control": {
            "type": "image"
          },
          "description": "Pick from the media library (Browse…)"
        }
      ]
    }
  ]
};

export const registry = new Registry(spec);

/** Author components for server rendering (public pages). */
export const serverComponents = { Callout, CallToAction, Column, FAQ, FAQItem, Feature, FeatureGrid, Hero, Html, LogoCloud, Newsletter, PricingTable, PricingTier, Stat, StatsBand, Testimonial, TwoColumn };

/** Historical alias for `serverComponents`. */
export const components = serverComponents;
