// GENERATED by `mdmx generate` — do not edit.
import { createElement, type ComponentType, type ReactNode } from "react";
import { notFound } from "next/navigation";
import { getEntries, getEntryBySlug, getStudioComponentDefs, type MDMXEntry } from "@mdmx/next";
import { MDMXContent } from "@mdmx/next/render";
import { studioRenderComponents } from "@mdmx/studio/react";
import { serverComponents } from "./registry.js";
import "./studio.css";

/** Collection name → directory, from mdmx.config.json. */
export const collections = {
  "posts": "content/posts"
} as const;

export type CollectionName = keyof typeof collections;

function dirOf(collection: CollectionName): string {
  const dir = collections[collection];
  if (!dir) throw new Error(`No collection "${String(collection)}" in mdmx.config.json.`);
  return dir;
}

export interface EntryQuery {
  /** Frontmatter status filter; defaults to published. */
  status?: string | string[] | null;
}

/** Entries of a collection, published-only unless asked otherwise. */
export async function listEntries(
  collection: CollectionName,
  query: EntryQuery = {},
): Promise<MDMXEntry[]> {
  const status = query.status === undefined ? "published" : query.status;
  return getEntries(dirOf(collection), status === null ? {} : { status });
}

/** One entry by slug, or null. */
export async function getEntry(
  collection: CollectionName,
  slug: string,
  query: EntryQuery = {},
): Promise<MDMXEntry | null> {
  const status = query.status === undefined ? "published" : query.status;
  return getEntryBySlug(dirOf(collection), decodeURIComponent(slug), status === null ? {} : { status });
}

/** Author components plus any studio components stored in the content repo. */
export async function renderComponents(): Promise<Record<string, ComponentType<any>>> {
  const defs = await getStudioComponentDefs("content");
  return { ...serverComponents, ...studioRenderComponents(defs) };
}

export interface MDMXEntryProps {
  collection: CollectionName;
  slug: string;
  status?: string | string[] | null;
  /** Extra or overriding components for this page. */
  components?: Record<string, ComponentType<any>>;
}

/**
 * Render one entry. Missing (or filtered out by status) means `notFound()`,
 * which is what a public route wants.
 */
export async function MDMXEntry({
  collection,
  slug,
  status,
  components,
}: MDMXEntryProps): Promise<ReactNode> {
  const entry = await getEntry(collection, slug, { status });
  if (!entry) notFound();
  const map = { ...(await renderComponents()), ...components };
  return createElement(MDMXContent, { source: entry.source, components: map });
}
