import { relative } from "node:path";
import type { RegistrySpec } from "@mdmx/core";
import type { MDMXConfig } from "@mdmx/project";
import type { ExtractedComponent } from "./extract.js";

/**
 * The generated convention layer (ADR-040).
 *
 * Package code can't import userland paths, but generated code can import
 * everything — so `.mdmx/` is where the wiring a consumer used to hand-write
 * now lives:
 *
 *   registry.json  data (the CLI, `mdmx check`, the API handlers)
 *   registry.ts    spec + `serverComponents` — server-safe, for public pages
 *   components.ts  the same map behind "use client", for the dashboard mount
 *   server.ts      bound `getEntry`/`MDMXEntry`, addressed by collection name
 *
 * Artifacts are committed (ADR-040), so they must be byte-stable: nothing
 * here embeds a timestamp, and `generate` skips the write when the hash is
 * unchanged.
 */

const BANNER = "// GENERATED by `mdmx generate` — do not edit.";

export interface EmittedFile {
  name: string;
  content: string;
}

export function emitRegistryModule(
  spec: RegistrySpec,
  components: readonly ExtractedComponent[],
  outDir: string,
): string {
  const lines: string[] = [BANNER, 'import { Registry, type RegistrySpec } from "@mdmx/core";'];
  lines.push(...importLines(components, outDir));
  const names = components.map((c) => c.spec.name);
  lines.push(
    "",
    `export const spec: RegistrySpec = ${JSON.stringify(spec, null, 2)};`,
    "",
    "export const registry = new Registry(spec);",
    "",
    "/** Author components for server rendering (public pages). */",
    `export const serverComponents = { ${names.join(", ")} };`,
    "",
    "/** Historical alias for `serverComponents`. */",
    "export const components = serverComponents;",
    "",
  );
  return lines.join("\n");
}

/**
 * The client map. Same imports, one directive — which is the whole reason
 * consumers used to keep two hand-written copies: a `"use client"` module
 * can't be imported by a server component, so the maps had to be separate
 * files even though their contents were identical.
 */
export function emitClientComponents(
  components: readonly ExtractedComponent[],
  outDir: string,
): string {
  const lines: string[] = ['"use client";', BANNER];
  lines.push(...importLines(components, outDir));
  const names = components.map((c) => c.spec.name);
  lines.push(
    "",
    "/** Author components for the editor canvas and the dashboard mount. */",
    `export const components = { ${names.join(", ")} };`,
    "",
  );
  return lines.join("\n");
}

/**
 * Bound server helpers: the public-page recipe with the config and the
 * component map already applied, so a page is a component call rather than an
 * assembly of readers, maps, and studio plumbing.
 */
export function emitServerModule(config: MDMXConfig, hasStudioCss: boolean): string {
  const collections = Object.entries(config.collections ?? {});
  const dirs = Object.fromEntries(collections.map(([name, c]) => [name, c.dir]));
  return `${BANNER}
import { createElement, type ComponentType, type ReactNode } from "react";
import { notFound } from "next/navigation";
import { getEntries, getEntryBySlug, getStudioComponentDefs, type MDMXEntry } from "@mdmx/next";
import { MDMXContent } from "@mdmx/next/render";
import { studioRenderComponents } from "@mdmx/studio/react";
import { serverComponents } from "./registry";${hasStudioCss ? '\nimport "./studio.css";' : ""}

/** Collection name → directory, from mdmx.config.json. */
export const collections = ${JSON.stringify(dirs, null, 2)} as const;

export type CollectionName = keyof typeof collections;

function dirOf(collection: CollectionName): string {
  const dir = collections[collection];
  if (!dir) throw new Error(\`No collection "\${String(collection)}" in mdmx.config.json.\`);
  return dir;
}

export interface EntryQuery {
  /** Frontmatter status filter; defaults to published. */
  status?: string | string[] | null;
}

/** Entries of a collection, published-only unless asked otherwise. */
export async function listEntries(
  collection: CollectionName,
  query: EntryQuery = {},
): Promise<MDMXEntry[]> {
  const status = query.status === undefined ? "published" : query.status;
  return getEntries(dirOf(collection), status === null ? {} : { status });
}

/** One entry by slug, or null. */
export async function getEntry(
  collection: CollectionName,
  slug: string,
  query: EntryQuery = {},
): Promise<MDMXEntry | null> {
  const status = query.status === undefined ? "published" : query.status;
  return getEntryBySlug(dirOf(collection), decodeURIComponent(slug), status === null ? {} : { status });
}

/** Author components plus any studio components stored in the content repo. */
export async function renderComponents(): Promise<Record<string, ComponentType<any>>> {
  const defs = await getStudioComponentDefs(${JSON.stringify(config.contentDir)});
  return { ...serverComponents, ...studioRenderComponents(defs) };
}

export interface MDMXEntryProps {
  collection: CollectionName;
  slug: string;
  status?: string | string[] | null;
  /** Extra or overriding components for this page. */
  components?: Record<string, ComponentType<any>>;
}

/**
 * Render one entry. Missing (or filtered out by status) means \`notFound()\`,
 * which is what a public route wants.
 */
export async function MDMXEntry({
  collection,
  slug,
  status,
  components,
}: MDMXEntryProps): Promise<ReactNode> {
  const entry = await getEntry(collection, slug, { status });
  if (!entry) notFound();
  const map = { ...(await renderComponents()), ...components };
  return createElement(MDMXContent, { source: entry.source, components: map });
}
`;
}

function importLines(components: readonly ExtractedComponent[], outDir: string): string[] {
  return components.map((c) => {
    const importPath = toImportPath(relative(outDir, c.file));
    if (c.exportName === "default") return `import ${c.spec.name} from "${importPath}";`;
    if (c.exportName === c.spec.name) return `import { ${c.spec.name} } from "${importPath}";`;
    return `import { ${c.exportName} as ${c.spec.name} } from "${importPath}";`;
  });
}

function toImportPath(rel: string): string {
  const posix = rel.split("\\").join("/");
  const noExt = posix.replace(/\.(tsx|ts|jsx|js)$/, "");
  return noExt.startsWith(".") ? noExt : `./${noExt}`;
}
