import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { glob } from "tinyglobby";
import {
  IMDX_SPEC_VERSION,
  type CollectionSpec,
  type FrontmatterField,
  type RegistrySpec,
} from "@imdx/core";
import type { IMDXConfig } from "./config.js";
import {
  extractComponents,
  type ExtractionIssue,
  type ExtractedComponent,
} from "./extract.js";

export interface GenerateResult {
  spec: RegistrySpec;
  issues: ExtractionIssue[];
  /** Absolute paths of the emitted artifacts. */
  written: { json: string; ts: string };
  hasErrors: boolean;
}

export async function generate(cwd: string, config: IMDXConfig): Promise<GenerateResult> {
  const patterns = Array.isArray(config.components)
    ? config.components
    : [config.components];
  const files = await glob(patterns, { cwd, absolute: true });

  const { components, issues } = extractComponents(files, cwd);

  // Registry-level validation: duplicate names.
  const seen = new Map<string, ExtractedComponent>();
  const deduped: ExtractedComponent[] = [];
  for (const c of components) {
    const existing = seen.get(c.spec.name);
    if (existing) {
      issues.push({
        severity: "error",
        message: `Duplicate component name "${c.spec.name}" (also defined in ${existing.spec.source}).`,
        file: c.spec.source ?? c.file,
      });
      continue;
    }
    seen.set(c.spec.name, c);
    deduped.push(c);
  }
  deduped.sort((a, b) => a.spec.name.localeCompare(b.spec.name));

  const collections = normalizeCollections(config);

  const componentSpecs = deduped.map((c) => c.spec);
  const body = JSON.stringify({ components: componentSpecs, collections });
  const spec: RegistrySpec = {
    imdxRegistryVersion: IMDX_SPEC_VERSION,
    generatedAt: new Date().toISOString(),
    hash: createHash("sha256").update(body).digest("hex").slice(0, 16),
    components: componentSpecs,
    ...(collections.length > 0 ? { collections } : {}),
  };

  const outDir = join(cwd, config.outDir);
  mkdirSync(outDir, { recursive: true });

  const jsonPath = join(outDir, "registry.json");
  writeFileSync(jsonPath, JSON.stringify(spec, null, 2) + "\n");

  const tsPath = join(outDir, "registry.ts");
  writeFileSync(tsPath, emitRegistryModule(spec, deduped, outDir));

  return {
    spec,
    issues,
    written: { json: jsonPath, ts: tsPath },
    hasErrors: issues.some((i) => i.severity === "error"),
  };
}

/**
 * Emit the binding module. The spec is inlined (rather than imported from
 * registry.json) to avoid JSON-module interop differences across bundlers.
 */
function emitRegistryModule(
  spec: RegistrySpec,
  components: ExtractedComponent[],
  outDir: string,
): string {
  const lines: string[] = [
    "// GENERATED by `imdx generate` — do not edit.",
    'import { Registry, type RegistrySpec } from "@imdx/core";',
  ];

  const names: string[] = [];
  for (const c of components) {
    const importPath = toImportPath(relative(outDir, c.file));
    if (c.exportName === "default") {
      lines.push(`import ${c.spec.name} from "${importPath}";`);
    } else if (c.exportName === c.spec.name) {
      lines.push(`import { ${c.spec.name} } from "${importPath}";`);
    } else {
      lines.push(`import { ${c.exportName} as ${c.spec.name} } from "${importPath}";`);
    }
    names.push(c.spec.name);
  }

  lines.push(
    "",
    `export const spec: RegistrySpec = ${JSON.stringify(spec, null, 2)};`,
    "",
    "export const registry = new Registry(spec);",
    "",
    `export const components = { ${names.join(", ")} };`,
    "",
  );
  return lines.join("\n");
}

/** Normalize the config's `collections` map into sorted `CollectionSpec[]`. */
function normalizeCollections(config: IMDXConfig): CollectionSpec[] {
  const out: CollectionSpec[] = [];
  for (const [name, c] of Object.entries(config.collections ?? {})) {
    const fields: FrontmatterField[] = Object.entries(c.fields).map(([fname, f]) => ({
      name: fname,
      required: f.required ?? false,
      control: f.control,
      ...(f.default !== undefined ? { default: f.default } : {}),
      ...(f.description ? { description: f.description } : {}),
    }));
    out.push({ name, dir: c.dir, fields });
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

function toImportPath(rel: string): string {
  const posix = rel.split("\\").join("/");
  const noExt = posix.replace(/\.(tsx|ts|jsx|js)$/, "");
  return noExt.startsWith(".") ? noExt : `./${noExt}`;
}
