import { readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { StudioComponentDef, TemplateChild, TemplateElement } from "@mdmx/studio";

/**
 * Studio component styling, compiled at build time (ADR-042).
 *
 * Studio components are authored in the browser and stored as JSON, so their
 * Tailwind-style classes never pass through the host app's CSS build. The
 * previous answer was a Tailwind browser runtime on public pages — a
 * third-party CDN script that compiles CSS after load. Instead, `mdmx
 * generate` extracts the classes and compiles a static stylesheet that rides
 * the app's normal CSS pipeline; Tailwind is a CLI dependency and never
 * reaches the app bundle.
 */

/** Every class name referenced by a set of studio definitions, sorted. */
export function extractStudioClasses(defs: readonly StudioComponentDef[]): string[] {
  const out = new Set<string>();
  const walkElement = (el: TemplateElement): void => {
    for (const cls of (el.classes ?? "").split(/\s+/)) {
      if (cls) out.add(cls);
    }
    for (const child of el.children ?? []) walkChild(child);
  };
  const walkChild = (child: TemplateChild): void => {
    if ("text" in child || "slot" in child) return;
    walkElement(child);
  };
  for (const def of defs) walkElement(def.template);
  return [...out].sort();
}

const INPUT_CSS = `@layer theme, base, components, utilities;
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/utilities.css" layer(utilities);`;

export interface CompileStudioCssResult {
  css: string;
  classes: string[];
  /** False when Tailwind isn't installed and only a class manifest was made. */
  compiled: boolean;
}

/**
 * Compile the utilities those classes need.
 *
 * Preflight is deliberately excluded: it would reset the author's own styles
 * on a public page, and studio components are guests there, not the design
 * system.
 */
export async function compileStudioCss(
  defs: readonly StudioComponentDef[],
): Promise<CompileStudioCssResult> {
  const classes = extractStudioClasses(defs);
  if (classes.length === 0) return { css: "", classes, compiled: true };

  let compile: typeof import("tailwindcss").compile;
  let root: string;
  try {
    ({ compile } = await import("tailwindcss"));
    // The stylesheet entry points sit at the package root, next to dist/.
    root = resolve(dirname(fileURLToPath(import.meta.resolve("tailwindcss"))), "..");
  } catch {
    return { css: manifestOnly(classes), classes, compiled: false };
  }

  const compiler = await compile(INPUT_CSS, {
    base: root,
    loadStylesheet: async (id: string) => {
      const file = join(root, id.replace(/^tailwindcss\//, ""));
      return { path: file, base: dirname(file), content: await readFile(file, "utf8") };
    },
  });

  const css = compiler.build([...classes]);
  return { css: `${header(classes)}\n${css}`, classes, compiled: true };
}

function header(classes: readonly string[]): string {
  return `/* GENERATED by \`mdmx generate\` — do not edit.
 * Utilities for ${classes.length} class name(s) used by studio components.
 * Preflight is excluded on purpose: these components render inside your pages. */`;
}

/**
 * Without Tailwind installed we still emit the class manifest, so a host that
 * runs its own Tailwind build can pick it up with one `@source` line rather
 * than losing studio styling silently.
 */
function manifestOnly(classes: readonly string[]): string {
  return `${header(classes)}
/* Tailwind is not installed here, so no utilities were compiled.
 * Either install it (pnpm add -D tailwindcss) or point your own Tailwind
 * build at this file:  @source "./.mdmx/studio.css";
 * Classes in use: ${classes.join(" ")} */
`;
}
