import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { loadConfig, type MDMXConfig } from "@mdmx/project";
import { check } from "../src/check.js";
import { generate } from "../src/generate.js";
import { emitStudioManifest } from "../src/studio-css.js";

const FIXTURE = join(__dirname, "fixture-app");

let app: string;
let config: MDMXConfig;

const PROMO = JSON.stringify({
  mdmxStudioVersion: 1,
  name: "Promo",
  props: [{ name: "title", type: "string", required: true }],
  template: {
    tag: "section",
    classes: "rounded-2xl bg-slate-900 p-8 text-white",
    children: [{ tag: "h2", classes: "text-2xl font-semibold", children: [{ text: "{props.title}" }] }],
  },
});

beforeEach(async () => {
  app = mkdtempSync(join(tmpdir(), "mdmx-handoff-"));
  cpSync(FIXTURE, app, { recursive: true });
  mkdirSync(join(app, "content", "_components"), { recursive: true });
  writeFileSync(join(app, "content", "_components", "Promo.json"), PROMO);
  ({ config } = await loadConfig(app));
});

afterEach(() => rmSync(app, { recursive: true, force: true }));

/** Make `tailwindcss` resolvable from the app root, as an installed host would have it. */
function installTailwindStub(root: string): void {
  mkdirSync(join(root, "node_modules", "tailwindcss"), { recursive: true });
  writeFileSync(
    join(root, "node_modules", "tailwindcss", "package.json"),
    JSON.stringify({ name: "tailwindcss", version: "4.0.0" }),
  );
}

describe("studio Tailwind handoff (ADR-054)", () => {
  it("emits one class per line and nothing else", () => {
    expect(emitStudioManifest(["a", "b-2"])).toBe("a\nb-2\n");
    expect(emitStudioManifest([])).toBe("");
  });

  it("a Tailwind host gets the class manifest, no studio.css, and a server.ts without the import", async () => {
    installTailwindStub(app);
    const result = await generate(app, config);
    expect(result.hasErrors).toBe(false);
    const manifest = join(app, ".mdmx", "studio-classes.txt");
    expect(existsSync(manifest)).toBe(true);
    expect(readFileSync(manifest, "utf8").split("\n").filter(Boolean)).toEqual([
      "bg-slate-900",
      "font-semibold",
      "p-8",
      "rounded-2xl",
      "text-2xl",
      "text-white",
    ]);
    expect(existsSync(join(app, ".mdmx", "studio.css"))).toBe(false);
    expect(readFileSync(join(app, ".mdmx", "server.ts"), "utf8")).not.toContain("studio.css");
  });

  it("check warns until a stylesheet scans the manifest", async () => {
    installTailwindStub(app);
    await generate(app, config);
    let result = await check(app, config);
    expect(result.studioWarning).toContain("@source");
    expect(result.studioWarning).toContain(".mdmx/studio-classes.txt");

    mkdirSync(join(app, "app"), { recursive: true });
    writeFileSync(
      join(app, "app", "globals.css"),
      '@import "tailwindcss";\n@source "../.mdmx/studio-classes.txt";\n',
    );
    result = await check(app, config);
    expect(result.studioWarning).toBeNull();
  });

  it("a host without Tailwind still gets compiled studio.css (ADR-042) and no manifest", async () => {
    const result = await generate(app, config);
    expect(result.hasErrors).toBe(false);
    expect(existsSync(join(app, ".mdmx", "studio-classes.txt"))).toBe(false);
    // The CLI has Tailwind as its own dependency, so the sheet is real CSS.
    const css = readFileSync(join(app, ".mdmx", "studio.css"), "utf8");
    expect(css).toContain("GENERATED by `mdmx generate`");
    expect(readFileSync(join(app, ".mdmx", "server.ts"), "utf8")).toContain('import "./studio.css"');
    expect((await check(app, config)).studioWarning).toBeNull();
  });

  it("switching a host to Tailwind removes the stale compiled sheet", async () => {
    await generate(app, config);
    expect(existsSync(join(app, ".mdmx", "studio.css"))).toBe(true);
    installTailwindStub(app);
    await generate(app, config);
    expect(existsSync(join(app, ".mdmx", "studio.css"))).toBe(false);
    expect(existsSync(join(app, ".mdmx", "studio-classes.txt"))).toBe(true);
  });
});
